// lib/legal/terms-content.tsx
import type { LegalDoc } from './types'

const SUPPORT_EMAIL = (
  <a
    href="mailto:info@lynqagency.com"
    className="text-[var(--primary)] hover:underline"
  >
    info@lynqagency.com
  </a>
)

export const termsDoc: LegalDoc = {
  title: 'Terms of Service',
  lastUpdated: 'June 1, 2026',
  intro: (
    <>
      <p><strong className="text-[var(--foreground)]">Company Information</strong></p>
      <p>Welcome to Lynq &amp; Flow.</p>
      <p>
        Lynq &amp; Flow is an AI-powered Shopify helpdesk and automation platform
        that enables automated and AI-assisted customer communication, order
        management, and workflow optimisation for merchants operating on the
        Shopify Platform. The Service connects directly with the Customer&rsquo;s
        Shopify store through secure API authorisation and may generate,
        process, or analyse text, data, or other content using algorithmic and
        machine-learning functionality. It may also include related
        applications, integrations, and add-ons (collectively, the &ldquo;Service&rdquo;).
      </p>
      <p>The Service is provided by:</p>
      <p>
        Lynq &amp; Flow LLC, a limited liability company formed under the laws of
        the State of Wyoming, United States of America.
      </p>
      <p><strong className="text-[var(--foreground)]">Legal Details:</strong></p>
      <ul className="list-disc pl-5 space-y-1.5">
        <li>Legal Name: Lynq &amp; Flow LLC</li>
        <li>Type: Limited Liability Company (Wyoming)</li>
        <li>State of Formation: Wyoming, USA</li>
        <li>Date of Formation: April 30, 2026</li>
        <li>Delayed Effective Date: May 1, 2026</li>
        <li>Entity ID: 2026-001965184</li>
        <li>EIN: 98-1936010</li>
        <li>Duration: Perpetual</li>
        <li>Registered Agent: Registered Agents Inc</li>
        <li>Registered Address: 30 N Gould St Ste R, Sheridan, WY 82801, USA</li>
        <li>Contact Email: {SUPPORT_EMAIL}</li>
      </ul>
      <p>
        These Terms of Service (these &ldquo;Terms&rdquo;), together with any applicable
        order form, subscription, Shopify billing confirmation, or other
        agreement (each, an &ldquo;Order Form&rdquo;), form a legally binding agreement
        between Lynq &amp; Flow LLC (&ldquo;Company&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;) and the
        customer (&ldquo;Customer&rdquo;, &ldquo;you&rdquo;).
      </p>
      <p>By installing, accessing, or using the Service, you agree to be bound by these Terms.</p>
      <p>If you do not agree, you must not use the Service.</p>
    </>
  ),
  sections: [
    {
      id: 'definitions',
      number: '1',
      title: 'Definitions',
      body: (
        <dl className="space-y-3">
          <div>
            <dt className="font-medium text-[var(--foreground)]">&ldquo;Account&rdquo;</dt>
            <dd>Shopify-connected merchant account used to access the Service.</dd>
          </div>
          <div>
            <dt className="font-medium text-[var(--foreground)]">&ldquo;Customer Data&rdquo;</dt>
            <dd>any data submitted or processed through the Service by or on behalf of the Customer.</dd>
          </div>
          <div>
            <dt className="font-medium text-[var(--foreground)]">&ldquo;Customer / Merchant&rdquo;</dt>
            <dd>Shopify store owner using the Service.</dd>
          </div>
          <div>
            <dt className="font-medium text-[var(--foreground)]">&ldquo;Fees&rdquo;</dt>
            <dd>subscription or usage charges processed via Shopify billing.</dd>
          </div>
          <div>
            <dt className="font-medium text-[var(--foreground)]">&ldquo;Output&rdquo;</dt>
            <dd>any results generated by the Service.</dd>
          </div>
          <div>
            <dt className="font-medium text-[var(--foreground)]">&ldquo;Shopify Platform&rdquo;</dt>
            <dd>Shopify APIs, infrastructure, and services.</dd>
          </div>
          <div>
            <dt className="font-medium text-[var(--foreground)]">&ldquo;Subscription Term&rdquo;</dt>
            <dd>duration of active subscription.</dd>
          </div>
        </dl>
      ),
    },
    {
      id: 'scope-of-the-service',
      number: '2',
      title: 'Scope of the Service',
      body: (
        <>
          <h3 className="text-base font-medium text-[var(--foreground)] mt-6 mb-2">2.1 Licence</h3>
          <p>
            We grant you a limited, non-exclusive, non-transferable, revocable
            licence to use the Service solely for internal business purposes as
            a Shopify merchant.
          </p>
          <h3 className="text-base font-medium text-[var(--foreground)] mt-6 mb-2">2.2 Shopify Dependency</h3>
          <p>
            The Service depends on Shopify APIs and infrastructure. We are not
            responsible for Shopify outages, restrictions, or API changes.
          </p>
          <h3 className="text-base font-medium text-[var(--foreground)] mt-6 mb-2">2.3 Service Changes</h3>
          <p>
            We may update or improve the Service. If core functionality is
            materially reduced, we will provide reasonable prior notice.
          </p>
          <h3 className="text-base font-medium text-[var(--foreground)] mt-6 mb-2">2.4 Third-Party Services</h3>
          <p>
            We may integrate third-party services. We are not responsible for
            their performance or availability.
          </p>
        </>
      ),
    },
    {
      id: 'customer-obligations',
      number: '3',
      title: 'Customer Obligations',
      body: (
        <>
          <p>You agree to:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>maintain accurate account and billing information</li>
            <li>comply with applicable laws and Shopify policies</li>
            <li>be responsible for all actions under your account</li>
            <li>review and validate all Outputs before use</li>
            <li>ensure authorised users comply with these Terms</li>
          </ul>
          <p>You remain solely responsible for decisions made based on Outputs.</p>
        </>
      ),
    },
    {
      id: 'restrictions',
      number: '4',
      title: 'Restrictions',
      body: (
        <>
          <p>You must not:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>reverse engineer or extract source code</li>
            <li>resell or sublicense the Service</li>
            <li>use the Service for unlawful purposes</li>
            <li>build competing products using Outputs</li>
            <li>bypass security mechanisms</li>
            <li>share credentials with unauthorised users</li>
          </ul>
        </>
      ),
    },
    {
      id: 'fees-and-payment',
      number: '5',
      title: 'Fees and Payment',
      body: (
        <>
          <h3 className="text-base font-medium text-[var(--foreground)] mt-6 mb-2">5.1 Billing</h3>
          <p>
            All Fees are processed via Shopify billing system. You authorise
            Shopify to charge applicable Fees.
          </p>
          <h3 className="text-base font-medium text-[var(--foreground)] mt-6 mb-2">5.2 Taxes</h3>
          <p>
            Fees are exclusive of taxes. You are responsible for VAT or similar
            charges.
          </p>
          <h3 className="text-base font-medium text-[var(--foreground)] mt-6 mb-2">5.3 Pricing Changes</h3>
          <p>
            We may update pricing with 30 days&rsquo; notice. Changes apply from the
            next billing cycle.
          </p>
        </>
      ),
    },
    {
      id: 'intellectual-property',
      number: '6',
      title: 'Intellectual Property',
      body: (
        <>
          <p>
            All rights in the Service remain the exclusive property of Lynq &amp;
            Flow LLC or its licensors.
          </p>
          <p>The Service is licensed, not sold.</p>
          <p>You retain ownership of Customer Data.</p>
          <p>
            Subject to payment, you retain rights to Outputs excluding
            underlying systems.
          </p>
          <p>Feedback may be used freely by the Company.</p>
        </>
      ),
    },
    {
      id: 'protection-of-intellectual-property',
      number: '6A',
      title: 'Protection of Intellectual Property',
      body: (
        <>
          <p>You acknowledge that:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>the Service is protected by IP laws</li>
            <li>no rights are granted beyond the licence</li>
            <li>all rights not expressly granted are reserved</li>
          </ul>
          <p>You must not:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>copy or modify the Service</li>
            <li>remove branding or notices</li>
            <li>reverse engineer or decompile systems</li>
            <li>create competing products</li>
          </ul>
          <p>Unauthorised use is a material breach.</p>
        </>
      ),
    },
    {
      id: 'protection-of-ai-systems',
      number: '6B',
      title: 'Protection of AI Systems',
      body: (
        <>
          <p>
            You acknowledge that the Service includes proprietary AI systems
            and trade secrets.
          </p>
          <p>You must not:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>extract or replicate models or prompts</li>
            <li>use bots, scrapers, or crawlers</li>
            <li>attempt jailbreaks or prompt injection</li>
            <li>reverse engineer system logic</li>
            <li>use Outputs to train competing AI systems</li>
          </ul>
          <p>We may monitor usage for security and abuse prevention.</p>
          <p>Violation may result in immediate termination.</p>
        </>
      ),
    },
    {
      id: 'data-protection-and-privacy',
      number: '7',
      title: 'Data Protection and Privacy',
      body: (
        <>
          <p>We process personal data according to our Privacy Policy.</p>
          <p>We act as:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Data Controller: account, billing, analytics, support, marketing</li>
            <li>Data Processor: Shopify merchant and end-customer data</li>
          </ul>
          <p>
            Processing is governed by a Data Processing Agreement (DPA) where
            required.
          </p>
        </>
      ),
    },
    {
      id: 'ai-assisted-features',
      number: '8',
      title: 'AI-Assisted Features',
      body: (
        <>
          <p>AI features are assistive only.</p>
          <p>You acknowledge:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>outputs require human review</li>
            <li>outputs are not professional advice</li>
            <li>no fully automated legal/financial decisions occur without review</li>
            <li>you are responsible for validation</li>
          </ul>
          <p>You must not input sensitive personal data into AI features.</p>
        </>
      ),
    },
    {
      id: 'data-security',
      number: '9',
      title: 'Data Security',
      body: (
        <>
          <p>We implement:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>encryption (in transit and at rest)</li>
            <li>access controls</li>
            <li>monitoring and logging</li>
            <li>security testing</li>
            <li>restricted access policies</li>
          </ul>
        </>
      ),
    },
    {
      id: 'indemnification',
      number: '10',
      title: 'Indemnification',
      body: (
        <>
          <p>
            You agree to indemnify Lynq &amp; Flow LLC against claims arising
            from:
          </p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>your use of the Service</li>
            <li>violation of law or these Terms</li>
            <li>Customer Data</li>
            <li>misuse of Outputs</li>
          </ul>
        </>
      ),
    },
    {
      id: 'warranties-disclaimer',
      number: '11',
      title: 'Warranties Disclaimer',
      body: (
        <>
          <p>The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;.</p>
          <p>We do not guarantee:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>uninterrupted service</li>
            <li>error-free operation</li>
            <li>accuracy or suitability of Outputs</li>
          </ul>
        </>
      ),
    },
    {
      id: 'limitation-of-liability',
      number: '12',
      title: 'Limitation of Liability',
      body: (
        <>
          <p>To the maximum extent permitted by law:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>liability is limited to Fees paid in the last 6 months</li>
            <li>we are not liable for indirect damages</li>
            <li>including loss of profits, revenue, data, or business interruption</li>
          </ul>
        </>
      ),
    },
    {
      id: 'term-and-termination',
      number: '13',
      title: 'Term and Termination',
      body: (
        <>
          <p>You may terminate by uninstalling the Service via Shopify.</p>
          <p>We may suspend or terminate if:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Terms are breached</li>
            <li>legal violations occur</li>
            <li>security risks arise</li>
          </ul>
          <p>Upon termination:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>access is disabled immediately</li>
            <li>data retained up to 30 days for export</li>
            <li>then deleted or anonymised unless required by law</li>
          </ul>
        </>
      ),
    },
    {
      id: 'governing-law-and-jurisdiction',
      number: '14',
      title: 'Governing Law and Jurisdiction',
      body: (
        <>
          <p>
            These Terms are governed by the laws of the State of Wyoming,
            United States of America.
          </p>
          <p>
            Disputes shall be resolved by competent courts or arbitration where
            applicable.
          </p>
        </>
      ),
    },
    {
      id: 'changes-to-terms',
      number: '15',
      title: 'Changes to Terms',
      body: (
        <>
          <p>We may update these Terms.</p>
          <p>Material changes will be communicated via:</p>
          <ul className="list-disc pl-5 space-y-1.5">
            <li>Service interface</li>
            <li>email notification</li>
          </ul>
          <p>Continued use = acceptance.</p>
        </>
      ),
    },
    {
      id: 'general-provisions',
      number: '16',
      title: 'General Provisions',
      body: (
        <ul className="list-disc pl-5 space-y-1.5">
          <li>Assignment allowed for Company, restricted for users</li>
          <li>Force Majeure applies</li>
          <li>Severability applies</li>
          <li>Entire Agreement includes Terms, Privacy Policy, and DPA</li>
          <li>Independent contractor relationship applies</li>
        </ul>
      ),
    },
    {
      id: 'contact',
      number: '17',
      title: 'Contact',
      body: (
        <>
          <p>
            Lynq &amp; Flow LLC<br />
            30 N Gould St Ste R<br />
            Sheridan, WY 82801<br />
            United States
          </p>
          <p>Email: {SUPPORT_EMAIL}</p>
        </>
      ),
    },
  ],
}
